#!/bin/bash
# 🎮 PS4 Rental - ЗАПУСК ПОЛНОЙ СИСТЕМЫ

echo "================================"
echo "🎮 PS4 Rental Admin System"
echo "================================"
echo ""
echo "Этап 1️⃣: Подготовка..."
echo ""

# Проверим есть ли node_modules
if [ ! -d "backend/node_modules" ]; then
  echo "📦 Устанавливаю зависимости backend..."
  cd backend
  npm install
  cd ..
fi

if [ ! -d "admin-panel/node_modules" ]; then
  echo "📦 Устанавливаю зависимости admin-panel..."
  cd admin-panel
  npm install
  cd ..
fi

echo ""
echo "✅ Подготовка завершена!"
echo ""
echo "================================"
echo "Этап 2️⃣: Запуск серверов..."
echo "================================"
echo ""
echo "ℹ️  Откройте ДВА терминала:"
echo ""
echo "📍 Терминал 1 (Backend):"
echo "   cd backend"
echo "   npm start"
echo ""
echo "📍 Терминал 2 (Frontend):"
echo "   cd admin-panel"
echo "   npm start"
echo ""
echo "================================"
echo "Когда серверы запустятся:"
echo "================================"
echo ""
echo "🌐 Откройте в браузере:"
echo "   http://localhost:3000"
echo ""
echo "📍 Логин:"
echo "   Username: admin"
echo "   Password: password"
echo ""
echo "🎮 Доступные функции:"
echo "   ✅ 📊 Статистика - Основные KPI"
echo "   ✅ 📈 Графики - Базовые графики с экспортом"
echo "   ✅ 📊 Аналитика - Расширенная аналитика со всеми метриками"
echo "   ✅ 📅 Календарь - Бронирование и управление аренды"
echo "   ✅ 📢 Уведомления - Отправка уведомлений пользователям"
echo "   ✅ ⚠️  Штрафы - Управление штрафами"
echo "   ✅ 🎮 Консоли - Управление консолями и фото"
echo "   ✅ 📋 Аренды - Управление арендами"
echo "   ✅ 👥 Пользователи - Управление пользователями"
echo ""
echo "================================"
echo "Backend endpoints:"
echo "================================"
echo ""
echo "🔗 Health Check:"
echo "   GET http://localhost:5000/api/health"
echo ""
echo "🔐 Аутентификация:"
echo "   POST /api/auth/login"
echo "   POST /api/auth/refresh"
echo "   POST /api/auth/logout"
echo ""
echo "📊 API Routes:"
echo "   GET  /api/consoles          - Получить консоли"
echo "   POST /api/consoles          - Добавить консоль"
echo "   GET  /api/rentals           - Получить аренды"
echo "   GET  /api/users             - Получить пользователей"
echo "   GET  /api/penalties         - Получить штрафы"
echo "   POST /api/penalties         - Добавить штраф"
echo "   GET  /api/notifications    - Получить уведомления"
echo "   POST /api/notifications/send - Отправить уведомление"
echo "   GET  /api/analytics/overview - Получить статистику"
echo "   GET  /api/analytics/extended - Расширенная аналитика"
echo "   POST /api/export/analytics/pdf - Экспортировать PDF"
echo "   POST /api/export/analytics/excel - Экспортировать Excel"
echo ""
echo "================================"
echo "Database Models:"
echo "================================"
echo ""
echo "Users, Consoles, Rentals, Penalties"
echo "Notifications, Reviews, Categories"
echo ""
echo "✅ MongoDB готовый к использованию!"
echo "✅ Все routes подключены!"
echo "✅ Готово к производству!"
echo ""
